#!/bin/sh

### BEGIN /etc/X11/xinit/xinitrc
userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# merge in defaults and keymaps

if [ -f $sysresources ]; then
    xrdb -merge $sysresources
fi

if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then
    xrdb -merge "$userresources"
fi

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi

# start some nice programs

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

### END   /etc/X11/xinit/xinitrc

#
# ~/.xinitrc
#
# Executed by startx (run your window manager from here)
#

#xrandr --output LVDS --off --output HDMI-2 --auto
export EDITOR="/usr/bin/vim"
export BROWSER=/usr/bin/chromium

## see: archlinx-wiki - X_resources#Getting_started
[[ -f ~/.Xresources ]] && xrdb -merge ~/.Xresources

## see: https://wiki.archlinux.org/index.php/SSH_Keys
## for ssh-agent support
keychain ~/.ssh/id_ecdsa ~/.ssh/id_rsa ~/.ssh/id_dsa
[ -f ~/.keychain/$HOSTNAME-sh ] && . ~/.keychain/$HOSTNAME-sh 2>/dev/null
[ -f ~/.keychain/$HOSTNAME-sh-gpg ] && . ~/.keychain/$HOSTNAME-sh-gpg 2>/dev/null

#
/usr/bin/xscreensaver -no-splash &

# exec gnome-session
# exec startkde
# exec startxfce4
# exec icewm
# exec openbox
# exec blackbox
# exec fluxbox
# exec ratpoison
# exec dwm
# ... or any other WM of your choosing ...
#exec dbus-launch --exit-with-session awesome

#exec ck-launch-session dbus-launch openbox-session
exec openbox-session

