#
# ~/.bashrc
#

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

## line wrap on window resize
shopt -s checkwinsize

## correct env.var. expand
shopt -s direxpand

#PS1='[\u@\h \W]\$ '
PS1='\[\e[1;32m\][\A \u@\h \W]\$\[\e[0m\] '

export EDITOR='vim'

if [ -f /usr/share/bash-completion/bash_completion ]; then
	source /usr/share/bash-completion/bash_completion
fi

# for python
if [ -f $HOME/.pythonrc.py ]; then
	export PYTHONSTARTUP=$HOME/.pythonrc.py
fi

# for vim/neovim
alias vim='nvim'

# for go
export GOROOT=$HOME/sdk/go
export GOPATH=$HOME/dev/go/gocode
export PATH=$GOPATH/bin:$GOROOT/bin:$PATH
alias mgo='GO111MODULE=on go'

# local scripts/binaries
export PATH=$HOME/bin:$PATH

## general use
alias ls='ls --color=auto'
alias ll='ls -lh --color=auto'

alias cp='cp --interactive'
alias mv='mv --interactive'
alias rm='rm --interactive'

alias df='df --human-readable'
alias du='du --human-readable'

alias scpresume="rsync --partial --progress --rsh=ssh"

## switch overlay displays
# laptop screen
alias switch2LCD="xvattr -a XV_CRTC -v 0"
# external screen
alias switch2EXT="xvattr -a XV_CRTC -v 1"

## ssh aliases
alias lxplus="ssh -YC binet@lxplus.cern.ch"

## FUSE
alias  flx="sshfs binet@lxplus.cern.ch:/afs/cern.ch/user/b/binet /home/binet/fuse-cern"
alias uflx="fusermount -u /home/binet/fuse-cern"

## get backspace to work everywhere
## see: http://www.ibb.net/~anne/keyboard/keyboard.html
if tty --quiet ; then
	stty erase '^?'
fi

## clear terminal buffers
alias cls="reset; echo -ne '\033c'"

## for cmd/go tab completion
## gotab comes from github.com/sbinet/gotab
complete -C gotab -o nospace go

## to enable powerline-go in the shell
## function _update_ps1() {
##     PS1="$(powerline-go -cwd-max-depth 2 -error $?)"
## }
## 
## if [ "$TERM" != "linux" ]; then
##     PROMPT_COMMAND="_update_ps1; $PROMPT_COMMAND"
## fi

## enable accents
setxkbmap -option compose:ralt

## for direnv. needs to be LAST
eval "$(direnv hook bash)"
