#
# ~/.bashrc
#

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

alias ls='ls --color=auto'
alias ll='ls -lh --color=auto'

PS1='[\u@\h \W]\$ '

export EDITOR='vim'

if [ -f /usr/share/bash-completion/bash_completion ]; then
	source /usr/share/bash-completion/bash_completion
fi

# if [ -f /usr/lib/python3.4/site-packages/powerline/bindings/bash/powerline.sh ]; then
#     source /usr/lib/python3.4/site-packages/powerline/bindings/bash/powerline.sh
# fi

# for go
export GOPATH=$HOME/dev/go/gocode
export PATH=$GOPATH/bin:$PATH

# local scripts/binaries
export PATH=$HOME/bin:$PATH

## general use
alias scpresume="rsync --partial --progress --rsh=ssh"

## switch overlay displays
# laptop screen
alias switch2LCD="xvattr -a XV_CRTC -v 0"
# external screen
alias switch2EXT="xvattr -a XV_CRTC -v 1"

## ssh aliases
alias lxplus="ssh -YC binet@lxplus.cern.ch"

## FUSE
alias  flx="sshfs binet@lxplus.cern.ch:/afs/cern.ch/user/b/binet /home/binet/fuse-cern"
alias uflx="fusermount -u /home/binet/fuse-cern"

## get backspace to work everywhere
## see: http://www.ibb.net/~anne/keyboard/keyboard.html
if tty --quiet ; then
	stty erase '^?'
fi

## clear terminal buffers
alias cls="echo -ne '\033c'"

## for direnv. needs to be LAST
eval "$(direnv hook bash)"

